version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hero_force
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: heroforce-backend
    restart: always
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: hero_force
      JWT_SECRET: sua_chave_secreta_aqui
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend/heroforce-web
      dockerfile: Dockerfile
    container_name: heroforce-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data: