export const CHARACTER  = [
  'Spider-Man',
  'Iron Man',
  'Captain America',
  'Thor',
  'Hulk',
  'Black Widow',
  'Hawkeye',
  'Doctor Strange',
  'Scarlet Witch',
  'Black Panther',
  'Captain Marvel',
  'Ant-Man',
  'Wasp',
  'Falcon',
  'Winter Soldier',
  'Star-Lord',
  'Gamora',
  'Drax',
  'Rocket Raccoon',
  'Groot',
  'Deadpool',
  'Wolverine',
  'Punisher',
  'Venom',
  'Loki',
  'Silver Surfer',
  'Blade',
  'Ghost Rider',
  'Moon Knight',
  'Shang-Chi',
  'Daredevil',
  'Elektra',
  'Nick Fury',
  'War Machine',
  'Vision',
  'Quicksilver',
  'Cable',
  'Bishop',
  'Iceman',
  'Angel',
  'Beast',
  'Jean Grey',
  'Cyclops',
  'Storm',
  'Kitty Pryde',
  'Colossus',
  'Magik',
  'Nova',
  'Sentry',
  'Hercules',
  'Batman',
  'Superman',
  'Wonder Woman',
  'The Flash',
  'Aquaman',
  'Cyborg',
  'Green Lantern',
  'Green Arrow',
  'Nightwing',
  'Robin',
  'Batgirl',
  'Supergirl',
  'Shazam',
  'John Constantine',
  'Zatanna',
  'Martian Manhunter',
  'Hawkman',
  'Hawkgirl',
  'Black Canary',
  'Blue Beetle',
  'Booster Gold',
  'Firestorm',
  'Red Hood',
  'Red Robin',
  'Batwoman',
  'Catwoman',
  'Harley Quinn',
  'Poison Ivy',
  'Swamp Thing',
  'Animal Man',
  'Spectre',
  'Doctor Fate',
  'Orion',
  'Big Barda',
  'Mister Miracle',
  'Lobo',
  'Black Adam',
  'Raven',
  'Starfire',
  'Beast Boy',
  'Cyborg Superman',
  'Power Girl',
  'Huntress',
  'Azrael',
  'Vixen',
  'Plastic Man',
   'Metamorpho',
  'Captain Atom',
  'Doomsday',
  'Hourman',
]