###list projects
GET http://localhost:3000/projects

###get projects
GET http://localhost:3000/projects/6b411c91-2398-4d27-b635-e11decef6a0e

###create projects
POST http://localhost:3000/projects/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3dlcXd0ZUBnbWFpbC5jb20iLCJzdWIiOiI1N2U2OWM5OS0wNmY2LTRkZTYtOTZhZi00N2QzMDA0YzJlM2QiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzUyMzU0MzgsImV4cCI6MTc3NTIzNTQ5OH0.t-kC1YfdZObwiQCF-zSWygLw-AtyeFl0iv0dMtJyu1g
Content-Type: application/json

{
  "name": "Project Name",
  "description": "Project Description",
  "status": "pendente",
  "goals": ["encantamento"],
  "userId": "57e69c99-06f6-4de6-96af-47d3004c2e3d"
}


###update projects
PATCH http://localhost:3000/projects/5dcc5c23-14b0-4032-9c8f-df29516934ae
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3dlcXd0ZUBnbWFpbC5jb20iLCJzdWIiOiI1N2U2OWM5OS0wNmY2LTRkZTYtOTZhZi00N2QzMDA0YzJlM2QiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzUyMzU4MTQsImV4cCI6MTc3NTIzNTg3NH0.h95WsQXroI-fqJjaDoylLKVKdAdqkOHZFns_P5ZnxwA
Content-Type: application/json

{
  "status": "em andamento"
}


###delete projects
DELETE http://localhost:3000/projects/5dcc5c23-14b0-4032-9c8f-df29516934ae
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3dlcXd0ZUBnbWFpbC5jb20iLCJzdWIiOiI1N2U2OWM5OS0wNmY2LTRkZTYtOTZhZi00N2QzMDA0YzJlM2QiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzUyMzU4MTQsImV4cCI6MTc3NTIzNTg3NH0.h95WsQXroI-fqJjaDoylLKVKdAdqkOHZFns_P5ZnxwA
Content-Type: application/json