###list projects
GET http://localhost:3000/projects

###get projects
GET http://localhost:3000/projects/6b411c91-2398-4d27-b635-e11decef6a0e

###get projects by userId
GET http://localhost:3000/projects/user/d6420467-b06a-402a-8f7a-f8216535882a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluMkBnbWFpbC5jb20iLCJzdWIiOiI4MjA3NjFlNi1mNjQxLTRiN2EtYmFjNi0xOTBiZjJiNWVlMmYiLCJyb2xlIjoidXNlciIsImlhdCI6MTc3NTM1MzU2MiwiZXhwIjoxNzc1MzY3OTYyfQ.spqslpN6pC6CEhueKsial7CwSo3WR8myPqjO5s3bXJw

###create projects
POST http://localhost:3000/projects/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInN1YiI6Ijc5YjNjZjA4LTFlZWYtNDMyMS1iODMxLTM1MzcyYWYyMDZhMCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3NTMwMTkzOCwiZXhwIjoxNzc1MzE2MzM4fQ.WC9xClT-jWm_Qyzu1LlvEG6fqwBF-dJK_VrDqYr3WYg
Content-Type: application/json

{
  "name": "Project Name",
  "description": "Project Description",
  "status": "pendente",
  "goals": ["encantamento"],
  "userId": "57e69c99-06f6-4de6-96af-47d3004c2e3d"
}


###update projects
PATCH http://localhost:3000/projects/9c847692-33ed-44d8-bd31-e1c3f3a72b1d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInN1YiI6Ijc5YjNjZjA4LTFlZWYtNDMyMS1iODMxLTM1MzcyYWYyMDZhMCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3NTI0NDE5MCwiZXhwIjoxNzc1MjU4NTkwfQ.L7BeX5apMAG8fUvRtHMTPp5YkfgYbi04LjRs3H92lP8
Content-Type: application/json

{
  "status": "em andamento"
}


###delete projects
DELETE http://localhost:3000/projects/5dcc5c23-14b0-4032-9c8f-df29516934ae
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3dlcXd0ZUBnbWFpbC5jb20iLCJzdWIiOiI1N2U2OWM5OS0wNmY2LTRkZTYtOTZhZi00N2QzMDA0YzJlM2QiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzUyMzU4MTQsImV4cCI6MTc3NTIzNTg3NH0.h95WsQXroI-fqJjaDoylLKVKdAdqkOHZFns_P5ZnxwA
Content-Type: application/json