### signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "admin2@gmail.com",
    "password": "adminadmin",
    "name": "admin",
    "character": "Wolverine",
    "role": "admin"
}

### signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "adminadmin"
}