### signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "admin2@gmail.com",
    "password": "acess_admin",
    "name": "Administrador",
    "character": "Wolverine",
    "role": "user"
}

### signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "admin2@gmail.com",
  "password": "acess_admin"
}